# Generated by Django 5.2.5 on 2025-08-26 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='trainee/images')),
                ('status', models.BooleanField(default=True)),
                ('trackid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='track.track')),
            ],
        ),
    ]
